language: ruby
sudo: false
cache: bundler
before_install: gem install bundler
rvm:
  - 2.2.5
  - 2.3.1
addons:
  code_climate:
    repo_token: 134e1f1cc8b60db4f2a491152c9227a6dbbfbeba5c1d05ee8b44cd78a1069f28
