name: build

on:
  push:
    branches: [ main, github-actions ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.2']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Install Dependency
        run: |
          gem install bundler
          bundle install

      - name: Run tests
        run: bundle exec rspec

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v4
        env:
          CC_TEST_REPORTER_ID: 134e1f1cc8b60db4f2a491152c9227a6dbbfbeba5c1d05ee8b44cd78a1069f28
