name: Daily update
on:
  schedule:
    - cron: 0 0 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
    - name: bundle and run rake update
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec rake update_donation_unit
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
